# This plugin uses BarAPI by James Mortemore (https://github.com/confuser/BarAPI)
# so the boss bar implementation was not written by me.
# I only added this API plugin code directly into my plugin
# so no one has to add a BarAPI plugin to their server.

name: KCaptcha
main: com.gmail.kamilkime.kcaptcha.Main
version: 1.4.1
author: Kamilkime
website: https://www.spigotmc.org/resources/authors/kamilkime.52851/

commands:
  kcaptcha:
    description: "Main KCaptcha plugin command"
    aliases: [captcha, kcode, code]